### ISSUE TITLE
Recommendation doesn't load

### ISSUE THREAD

**Issue by AndreiGheorghe1998** [kishan0725/AJAX-Movie-Recommendation-System-with-Sentiment-Analysis#11]
Hello sir, 

I'm facing an issue. I've modified the KEY in mentioned places, and after I search a movie and press Enter I don't receive anything regarding the movie or recommendations. 

Any idea why?

**Comment by kishan0725** [comment]
Check if you could see the API key in the network tab of your browser

**Comment by kishan0725** [comment]
Closing the issue due to inactivity

**Comment by friendlyved** [comment]
facing 
same issue please reply
