### ISSUE TITLE
Some positive sentiments are wrongly labelled.

### ISSUE THREAD

**Issue by dhivyasreedhar** [kishan0725/AJAX-Movie-Recommendation-System-with-Sentiment-Analysis#14]
![Capture](https://user-images.githubusercontent.com/71582226/132177563-eeb609e1-7c0a-4069-9238-63f35f40c339.PNG)

**Comment by kishan0725** [comment]
Hi @dhivyasreedhar. Thank you for bringing this to my attention. The dataset (reviews.txt) I used to train the model is not an exhaustive one and I didn't perform any performance tuning on my model. So, I think it's expected and you might see some of the reviews tagged with the wrong sentiments. 

If you have more data to train and tweak the parameters of the model to perform well on the training sets, you can do that too. Closing this issue. Feel free to reopen it if you still have some queries. Thanks.
