### ISSUE TITLE
Invalid Request Error

### ISSUE THREAD

**Issue by Nithyasree11** [kishan0725/AJAX-Movie-Recommendation-System-with-Sentiment-Analysis#5]
@kishan0725 Hats-off to your work . Your project is really amazing. I am getting invalid request error while running the application even after giving the correct API. Could you please help in resolving this issue.
![Screenshot (472)](https://user-images.githubusercontent.com/58833309/110084352-dd487d00-7db5-11eb-94f5-9a0635a65c12.png)

**Comment by kishan0725** [comment]
@Nithyasree11 Kindly go through this issue - https://github.com/kishan0725/The-Movie-Cinema/issues/2. This might help you get it resolved.

Thanks, btw :)

**Comment by Nithyasree11** [comment]
Thank you so much.
