### ISSUE TITLE
Regarding the background image and loader GIF

### ISSUE THREAD

**Issue by AishwaryaAllada** [kishan0725/AJAX-Movie-Recommendation-System-with-Sentiment-Analysis#8]
Hello.

How to completely change the background image and the loader GIF. Irrespective of making the changes in the "style.css" file and deleting the original image and GIF you had and replacing them with a new one is not making any changes to the UI. Can you tell me where else the necessary changes have to be made? 

Thanks.!

**Comment by kishan0725** [comment]
> Hello.
> 
> How to completely change the background image and the loader GIF. Irrespective of making the changes in the "style.css" file and deleting the original image and GIF you had and replacing them with a new one is not making any changes to the UI. Can you tell me where else the necessary changes have to be made?
> 
> Thanks.!

Once you made the changes in styles.css, make sure to press "ctrl+f5" in the browser, which is a hard refresh that refreshes browser cache as well.

**Comment by kishan0725** [comment]
Closing this issue as I've not heard anything from you. Feel free to reopen the issue if you still facing this problem. :)
